version: "3.3"
services:
  metaduck:
    container_name: metaduck
    image: metaduck:v0.48.1
    ports:
      - 80:3000
    volumes:
      - $PWD/db:/container/directory
    environment:
      - MB_PLUGINS_DIR=/home/plugins
