/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {Addr, AssetInfo, Binary, PairInfo} from "./types";
import {InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, ConfigResponse, PairsResponse} from "./OraiswapFactory.types";
export interface OraiswapFactoryReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  pair: ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }) => Promise<PairInfo>;
  pairs: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: AssetInfo[];
  }) => Promise<PairsResponse>;
}
export class OraiswapFactoryQueryClient implements OraiswapFactoryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.pair = this.pair.bind(this);
    this.pairs = this.pairs.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  pair = async ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }): Promise<PairInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair: {
        asset_infos: assetInfos
      }
    });
  };
  pairs = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: AssetInfo[];
  }): Promise<PairsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pairs: {
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface OraiswapFactoryInterface extends OraiswapFactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    owner,
    pairCodeId,
    tokenCodeId
  }: {
    owner?: string;
    pairCodeId?: number;
    tokenCodeId?: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createPair: ({
    assetInfos,
    pairAdmin
  }: {
    assetInfos: AssetInfo[];
    pairAdmin?: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addPair: ({
    pairInfo
  }: {
    pairInfo: PairInfo;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  migrateContract: ({
    contractAddr,
    msg,
    newCodeId
  }: {
    contractAddr: string;
    msg: Binary;
    newCodeId: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OraiswapFactoryClient extends OraiswapFactoryQueryClient implements OraiswapFactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.createPair = this.createPair.bind(this);
    this.addPair = this.addPair.bind(this);
    this.migrateContract = this.migrateContract.bind(this);
  }

  updateConfig = async ({
    owner,
    pairCodeId,
    tokenCodeId
  }: {
    owner?: string;
    pairCodeId?: number;
    tokenCodeId?: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        owner,
        pair_code_id: pairCodeId,
        token_code_id: tokenCodeId
      }
    }, _fee, _memo, _funds);
  };
  createPair = async ({
    assetInfos,
    pairAdmin
  }: {
    assetInfos: AssetInfo[];
    pairAdmin?: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_pair: {
        asset_infos: assetInfos,
        pair_admin: pairAdmin
      }
    }, _fee, _memo, _funds);
  };
  addPair = async ({
    pairInfo
  }: {
    pairInfo: PairInfo;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_pair: {
        pair_info: pairInfo
      }
    }, _fee, _memo, _funds);
  };
  migrateContract = async ({
    contractAddr,
    msg,
    newCodeId
  }: {
    contractAddr: string;
    msg: Binary;
    newCodeId: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      migrate_contract: {
        contract_addr: contractAddr,
        msg,
        new_code_id: newCodeId
      }
    }, _fee, _memo, _funds);
  };
}