/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {Addr, Uint128, Binary, AssetInfo, Decimal, Cw20ReceiveMsg, Asset, RewardMsg} from "./types";
import {InstantiateMsg, ExecuteMsg, QueryMsg, OldStoreType, MigrateMsg, AllStakersResponse, StakerResponse, ConfigResponse, ArrayOfQueryPoolInfoResponse, QueryPoolInfoResponse, PoolInfoResponse, RewardInfoResponse, RewardInfoResponseItem, ArrayOfRewardInfoResponse, RewardsPerSecResponse} from "./OraiswapStaking.types";
export interface OraiswapStakingReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  poolInfo: ({
    stakingToken
  }: {
    stakingToken: Addr;
  }) => Promise<PoolInfoResponse>;
  rewardsPerSec: ({
    stakingToken
  }: {
    stakingToken: Addr;
  }) => Promise<RewardsPerSecResponse>;
  rewardInfo: ({
    stakerAddr,
    stakingToken
  }: {
    stakerAddr: Addr;
    stakingToken?: Addr;
  }) => Promise<RewardInfoResponse>;
  rewardInfos: ({
    limit,
    order,
    stakingToken,
    startAfter
  }: {
    limit?: number;
    order?: number;
    stakingToken: Addr;
    startAfter?: Addr;
  }) => Promise<ArrayOfRewardInfoResponse>;
  getPoolsInformation: () => Promise<ArrayOfQueryPoolInfoResponse>;
  queryOldStore: ({
    storeType
  }: {
    storeType: OldStoreType;
  }) => Promise<Binary>;
  allStakers: () => Promise<AllStakersResponse>;
}
export class OraiswapStakingQueryClient implements OraiswapStakingReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.poolInfo = this.poolInfo.bind(this);
    this.rewardsPerSec = this.rewardsPerSec.bind(this);
    this.rewardInfo = this.rewardInfo.bind(this);
    this.rewardInfos = this.rewardInfos.bind(this);
    this.getPoolsInformation = this.getPoolsInformation.bind(this);
    this.queryOldStore = this.queryOldStore.bind(this);
    this.allStakers = this.allStakers.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  poolInfo = async ({
    stakingToken
  }: {
    stakingToken: Addr;
  }): Promise<PoolInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_info: {
        staking_token: stakingToken
      }
    });
  };
  rewardsPerSec = async ({
    stakingToken
  }: {
    stakingToken: Addr;
  }): Promise<RewardsPerSecResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      rewards_per_sec: {
        staking_token: stakingToken
      }
    });
  };
  rewardInfo = async ({
    stakerAddr,
    stakingToken
  }: {
    stakerAddr: Addr;
    stakingToken?: Addr;
  }): Promise<RewardInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_info: {
        staker_addr: stakerAddr,
        staking_token: stakingToken
      }
    });
  };
  rewardInfos = async ({
    limit,
    order,
    stakingToken,
    startAfter
  }: {
    limit?: number;
    order?: number;
    stakingToken: Addr;
    startAfter?: Addr;
  }): Promise<ArrayOfRewardInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_infos: {
        limit,
        order,
        staking_token: stakingToken,
        start_after: startAfter
      }
    });
  };
  getPoolsInformation = async (): Promise<ArrayOfQueryPoolInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_pools_information: {}
    });
  };
  queryOldStore = async ({
    storeType
  }: {
    storeType: OldStoreType;
  }): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_old_store: {
        store_type: storeType
      }
    });
  };
  allStakers = async (): Promise<AllStakersResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_stakers: {}
    });
  };
}
export interface OraiswapStakingInterface extends OraiswapStakingReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    migrateStoreStatus,
    owner,
    rewarder
  }: {
    migrateStoreStatus?: boolean;
    owner?: Addr;
    rewarder?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerAsset: ({
    stakingToken
  }: {
    stakingToken: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deprecateStakingToken: ({
    newStakingToken,
    stakingToken
  }: {
    newStakingToken: Addr;
    stakingToken: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateRewardsPerSec: ({
    assets,
    stakingToken
  }: {
    assets: Asset[];
    stakingToken: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  depositReward: ({
    rewards
  }: {
    rewards: RewardMsg[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unbond: ({
    amount,
    stakingToken
  }: {
    amount: Uint128;
    stakingToken: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    stakingToken
  }: {
    stakingToken?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawOthers: ({
    stakerAddrs,
    stakingToken
  }: {
    stakerAddrs: Addr[];
    stakingToken?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  autoStake: ({
    assets,
    slippageTolerance
  }: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  autoStakeHook: ({
    prevStakingTokenAmount,
    stakerAddr,
    stakingToken
  }: {
    prevStakingTokenAmount: Uint128;
    stakerAddr: Addr;
    stakingToken: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  migrateStore: ({
    assetInfo
  }: {
    assetInfo: AssetInfo;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OraiswapStakingClient extends OraiswapStakingQueryClient implements OraiswapStakingInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.registerAsset = this.registerAsset.bind(this);
    this.deprecateStakingToken = this.deprecateStakingToken.bind(this);
    this.updateRewardsPerSec = this.updateRewardsPerSec.bind(this);
    this.depositReward = this.depositReward.bind(this);
    this.unbond = this.unbond.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.withdrawOthers = this.withdrawOthers.bind(this);
    this.autoStake = this.autoStake.bind(this);
    this.autoStakeHook = this.autoStakeHook.bind(this);
    this.migrateStore = this.migrateStore.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, _fee, _memo, _funds);
  };
  updateConfig = async ({
    migrateStoreStatus,
    owner,
    rewarder
  }: {
    migrateStoreStatus?: boolean;
    owner?: Addr;
    rewarder?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        migrate_store_status: migrateStoreStatus,
        owner,
        rewarder
      }
    }, _fee, _memo, _funds);
  };
  registerAsset = async ({
    stakingToken
  }: {
    stakingToken: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_asset: {
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  deprecateStakingToken = async ({
    newStakingToken,
    stakingToken
  }: {
    newStakingToken: Addr;
    stakingToken: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deprecate_staking_token: {
        new_staking_token: newStakingToken,
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  updateRewardsPerSec = async ({
    assets,
    stakingToken
  }: {
    assets: Asset[];
    stakingToken: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_rewards_per_sec: {
        assets,
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  depositReward = async ({
    rewards
  }: {
    rewards: RewardMsg[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_reward: {
        rewards
      }
    }, _fee, _memo, _funds);
  };
  unbond = async ({
    amount,
    stakingToken
  }: {
    amount: Uint128;
    stakingToken: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unbond: {
        amount,
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  withdraw = async ({
    stakingToken
  }: {
    stakingToken?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  withdrawOthers = async ({
    stakerAddrs,
    stakingToken
  }: {
    stakerAddrs: Addr[];
    stakingToken?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_others: {
        staker_addrs: stakerAddrs,
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  autoStake = async ({
    assets,
    slippageTolerance
  }: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      auto_stake: {
        assets,
        slippage_tolerance: slippageTolerance
      }
    }, _fee, _memo, _funds);
  };
  autoStakeHook = async ({
    prevStakingTokenAmount,
    stakerAddr,
    stakingToken
  }: {
    prevStakingTokenAmount: Uint128;
    stakerAddr: Addr;
    stakingToken: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      auto_stake_hook: {
        prev_staking_token_amount: prevStakingTokenAmount,
        staker_addr: stakerAddr,
        staking_token: stakingToken
      }
    }, _fee, _memo, _funds);
  };
  migrateStore = async ({
    assetInfo
  }: {
    assetInfo: AssetInfo;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      migrate_store: {
        asset_info: assetInfo
      }
    }, _fee, _memo, _funds);
  };
}