/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {Addr, AssetInfo, Uint128, Binary, Decimal, Cw20ReceiveMsg, Asset, PairInfo} from "./types";
import {InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, String, PairResponse, PoolResponse, ReverseSimulationResponse, SimulationResponse, Boolean} from "./OraiswapPair.types";
export interface OraiswapPairReadOnlyInterface {
  contractAddress: string;
  pair: () => Promise<PairResponse>;
  pool: () => Promise<PoolResponse>;
  simulation: ({
    offerAsset
  }: {
    offerAsset: Asset;
  }) => Promise<SimulationResponse>;
  reverseSimulation: ({
    askAsset
  }: {
    askAsset: Asset;
  }) => Promise<ReverseSimulationResponse>;
  traderIsWhitelisted: ({
    trader
  }: {
    trader: Addr;
  }) => Promise<Boolean>;
  admin: () => Promise<String>;
}
export class OraiswapPairQueryClient implements OraiswapPairReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.pair = this.pair.bind(this);
    this.pool = this.pool.bind(this);
    this.simulation = this.simulation.bind(this);
    this.reverseSimulation = this.reverseSimulation.bind(this);
    this.traderIsWhitelisted = this.traderIsWhitelisted.bind(this);
    this.admin = this.admin.bind(this);
  }

  pair = async (): Promise<PairResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair: {}
    });
  };
  pool = async (): Promise<PoolResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool: {}
    });
  };
  simulation = async ({
    offerAsset
  }: {
    offerAsset: Asset;
  }): Promise<SimulationResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      simulation: {
        offer_asset: offerAsset
      }
    });
  };
  reverseSimulation = async ({
    askAsset
  }: {
    askAsset: Asset;
  }): Promise<ReverseSimulationResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reverse_simulation: {
        ask_asset: askAsset
      }
    });
  };
  traderIsWhitelisted = async ({
    trader
  }: {
    trader: Addr;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      trader_is_whitelisted: {
        trader
      }
    });
  };
  admin = async (): Promise<String> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin: {}
    });
  };
}
export interface OraiswapPairInterface extends OraiswapPairReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  provideLiquidity: ({
    assets,
    receiver,
    slippageTolerance
  }: {
    assets: Asset[];
    receiver?: Addr;
    slippageTolerance?: Decimal;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  swap: ({
    beliefPrice,
    maxSpread,
    offerAsset,
    to
  }: {
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  enableWhitelist: ({
    status
  }: {
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerTrader: ({
    traders
  }: {
    traders: Addr[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deregisterTrader: ({
    traders
  }: {
    traders: Addr[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OraiswapPairClient extends OraiswapPairQueryClient implements OraiswapPairInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.provideLiquidity = this.provideLiquidity.bind(this);
    this.swap = this.swap.bind(this);
    this.enableWhitelist = this.enableWhitelist.bind(this);
    this.registerTrader = this.registerTrader.bind(this);
    this.deregisterTrader = this.deregisterTrader.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, _fee, _memo, _funds);
  };
  provideLiquidity = async ({
    assets,
    receiver,
    slippageTolerance
  }: {
    assets: Asset[];
    receiver?: Addr;
    slippageTolerance?: Decimal;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      provide_liquidity: {
        assets,
        receiver,
        slippage_tolerance: slippageTolerance
      }
    }, _fee, _memo, _funds);
  };
  swap = async ({
    beliefPrice,
    maxSpread,
    offerAsset,
    to
  }: {
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      swap: {
        belief_price: beliefPrice,
        max_spread: maxSpread,
        offer_asset: offerAsset,
        to
      }
    }, _fee, _memo, _funds);
  };
  enableWhitelist = async ({
    status
  }: {
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      enable_whitelist: {
        status
      }
    }, _fee, _memo, _funds);
  };
  registerTrader = async ({
    traders
  }: {
    traders: Addr[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_trader: {
        traders
      }
    }, _fee, _memo, _funds);
  };
  deregisterTrader = async ({
    traders
  }: {
    traders: Addr[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deregister_trader: {
        traders
      }
    }, _fee, _memo, _funds);
  };
}