/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {Addr, InstantiateMsg, ExecuteMsg, Uint128, AssetInfo, Liquidity, Percentage, SwapOperation, AssetInfo2, Decimal, Asset, PoolKey, FeeTier, Route, QueryMsg, MigrateMsg, Config, ProtocolFee} from "./Zapper.types";
export interface ZapperReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  protocolFee: () => Promise<ProtocolFee>;
}
export class ZapperQueryClient implements ZapperReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.protocolFee = this.protocolFee.bind(this);
  }

  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  protocolFee = async (): Promise<ProtocolFee> => {
    return this.client.queryContractSmart(this.contractAddress, {
      protocol_fee: {}
    });
  };
}
export interface ZapperInterface extends ZapperReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    admin,
    dexV3,
    mixedRouter
  }: {
    admin?: Addr;
    dexV3?: Addr;
    mixedRouter?: Addr;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  zapInLiquidity: ({
    assetIn,
    minimumLiquidity,
    poolKey,
    routes,
    tickLowerIndex,
    tickUpperIndex
  }: {
    assetIn: Asset;
    minimumLiquidity?: Liquidity;
    poolKey: PoolKey;
    routes: Route[];
    tickLowerIndex: number;
    tickUpperIndex: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  zapOutLiquidity: ({
    positionIndex,
    routes
  }: {
    positionIndex: number;
    routes: Route[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerProtocolFee: ({
    feeReceiver,
    percent
  }: {
    feeReceiver: Addr;
    percent: Decimal;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ZapperClient extends ZapperQueryClient implements ZapperInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.zapInLiquidity = this.zapInLiquidity.bind(this);
    this.zapOutLiquidity = this.zapOutLiquidity.bind(this);
    this.registerProtocolFee = this.registerProtocolFee.bind(this);
  }

  updateConfig = async ({
    admin,
    dexV3,
    mixedRouter
  }: {
    admin?: Addr;
    dexV3?: Addr;
    mixedRouter?: Addr;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        admin,
        dex_v3: dexV3,
        mixed_router: mixedRouter
      }
    }, _fee, _memo, _funds);
  };
  zapInLiquidity = async ({
    assetIn,
    minimumLiquidity,
    poolKey,
    routes,
    tickLowerIndex,
    tickUpperIndex
  }: {
    assetIn: Asset;
    minimumLiquidity?: Liquidity;
    poolKey: PoolKey;
    routes: Route[];
    tickLowerIndex: number;
    tickUpperIndex: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      zap_in_liquidity: {
        asset_in: assetIn,
        minimum_liquidity: minimumLiquidity,
        pool_key: poolKey,
        routes,
        tick_lower_index: tickLowerIndex,
        tick_upper_index: tickUpperIndex
      }
    }, _fee, _memo, _funds);
  };
  zapOutLiquidity = async ({
    positionIndex,
    routes
  }: {
    positionIndex: number;
    routes: Route[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      zap_out_liquidity: {
        position_index: positionIndex,
        routes
      }
    }, _fee, _memo, _funds);
  };
  registerProtocolFee = async ({
    feeReceiver,
    percent
  }: {
    feeReceiver: Addr;
    percent: Decimal;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_protocol_fee: {
        fee_receiver: feeReceiver,
        percent
      }
    }, _fee, _memo, _funds);
  };
}