/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cosmosTokenSol from "./CosmosToken.sol";
export type { cosmosTokenSol };
export type { Bridge } from "./Bridge";
export type { DummyToken } from "./DummyToken";
export type { Gravity } from "./Gravity";
export type { IGravity } from "./IGravity";
