name: Check the test before merge

on:
  # When Release Pull Request is merged
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - staging

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        node: ["18.18.0"]
        os: ["runner04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)"  >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run nx reset workspace
        run: yarn nx reset

      - name: Run build
        run: yarn build

      - name: Run test
        run: |
          yarn test
